import { IsString, IsNotEmpty, IsPositive, Length, IsEmail, IsOptional, IsNumber } from 'class-validator'

import { IUsersCreateDTO } from '../../interfaces/IUser'
import { dtoValidationMessageHandler } from '../../validation/dtoMsgHandler'
import { ApiProperty } from '@nestjs/swagger'

const dtoMsg = new dtoValidationMessageHandler('User')

export class CreateUserDto implements IUsersCreateDTO {

    //used by app.useGlobalPipes(new ValidationPipe({
    // validators:
    // https://github.com/typestack/class-validator?tab=readme-ov-file#validation-messages
    /**
    @IsOptional()
    @IsPositive()
    @Max(1000)
    @IsInt()
    @IsEmail()
    @IsNumberString()
    @IsNotEmpty()
    @IsString()
    @Length(10, 20)
    @IsDate()
     */

    @ApiProperty({
        description: 'Имя пользователя',
        required: true,
        type: String
    })
    @IsNotEmpty({message: dtoMsg.getMessage('notempty')})
    @IsString({message: dtoMsg.getMessage('string')})
    @Length(2, 20, {message: dtoMsg.getMessage('length')})
    username: string

    @IsString({message: dtoMsg.getMessage('string')})
    @Length(3, 25, {message: dtoMsg.getMessage('length')})
    password: string

    @ApiProperty({
        description: 'Почта пользователя',
        required: true,
        type: String
    })
    @IsString()
    @IsEmail({ignore_max_length: true}, {message: dtoMsg.getMessage('email')})
    email: string

    @ApiProperty({
        description: 'Дата рождения, timestamp',
        required: true,
        type: String,
    })
    @IsOptional()
    birth: number

    @ApiProperty({
        description: 'Дата регистрации, autogenerated Date()',
        required: true,
        type: Number
    })
    @IsOptional()
    reg_date: number

    @ApiProperty({
        description: 'ID компании',
        required: true,
        type: String
    })
    @IsNotEmpty({message: dtoMsg.getMessage('notempty')})
    @IsNumber()
    @IsPositive()
    companyId: number

    @ApiProperty({
        description: 'Является ли руководителем компании',
        required: false,
        type: Boolean
    })
    isDirector: boolean

    @ApiProperty({
        description: 'Пол',
        required: false,
        type: Number
    })
    @IsNumber()
    gender: number;

    @ApiProperty({
        description: 'О себе',
        required: false,
        type: Boolean
    })
    @IsString()
    bio: string;

    @ApiProperty({
        description: 'Имя',
        required: false,
        type: Boolean
    })
    @IsString()
    firstName: string;

    @ApiProperty({
        description: 'Фамилия',
        required: false,
        type: Boolean
    })
    @IsString()
    lastName: string;

    @ApiProperty({
        description: 'Телефон',
        required: false,
        type: Boolean
    })
    @IsString()
    phone: string;




    constructor() {}

}